var internals = {
	system_id: 1,
	system_id2: "A",
	post_id: 1,
	page_id: 1,
	comment_id: 1,
	comment_id2: "A",
	user_id: 1,
	user_id2: "A",
	theme_id: 1,
	theme_id2: "A",
	is_published: 1,
	is_comments: 1,
	is_live: 1,
	is_on_menu: 1,
	page_order: 1,
	test_blog_name: "Test Name",
	test_blog_descr: "Test Description",
	test_email: "test@test.com",
	test_email2: "test2@test.com",
	test_email3: "test3@test.com",
	test_password: "1234",
	test_password2: "2345",
	test_title: "My Title",
	test_content: "My Content",
	test_theme_name: "My Theme Name",
	test_theme_description: "My Theme Description",
	comment_approval: true,
	comment_approval2: null,
	is_approved: true,
	white_hex: "FFFFFF",
	black_hex: "000000",
	theme_test_logo: "/path/to/file",
	theme_font_size: 12,
	theme_file: "blog menu",
	theme_file2: "index",
};

module.exports = internals;